---
- name: Update Sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list

- name: Update and upgrade apt packages
  become: yes
  become_user: root
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

- name: Install Packages
  become: yes
  become_user: root
  apt:
    pkg:
#     - virtualbox-guest-x11
#     - open-vm-tools
#     - open-vm-tools-desktop
      - make
      - gcc
      - unzip
      - firefox-esr
      - sqlite3
      - python
      - golang 
      - gparted
      - p7zip-full
      - zip
      - p7zip
      - curl
      - openssl
      - sudo
      - vim
      - net-tools
      - ttf-freefont
      - file-roller 
      - evince 
      - qalculate 
      - clementine 
      - vlc 
      - gimp 
      - shotwell 
      - gparted 
      - gnome-disk-utility 
      - libreoffice-writer 
      - libreoffice-calc 
      - libreoffice-impress 
      - shutter
      - libavcodec-extra 
      - ffmpeg
      - pavucontrol
      - apt-transport-https 
      - libcurl3
      - cherrytree
      - keepass2
      - evolution
      - git
    state: present

  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

- name: Upgrade Dist
  become: yes
  become_user: root
  apt:
    upgrade: dist
    update_cache: yes
    dpkg_options: 'force-confold,force-confdef'
  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

#- shell: uname -r
#  register: kernel
#
#- name: Install Linux Headers
#  become: yes
#  become_user: root
#  command: apt -y -qq install linux-headers-{{ item }}
#  with_items: "{{ kernel.stdout_lines }}"
#  register: apt_res
#  until: apt_res is success
#  retries: 10
#  delay: 3
#  ignore_errors: yes

- name: Remove mutt
  become: yes
  become_user: root
  apt: name=mutt state=absent
