---
- name: Install Packages
  become: yes
  become_user: root
  apt:
    pkg:
      - libappindicator3-1
      - keepass2
      - libqt5qml5
      - libqt5quick5
      - libqt5webkit5
      - qml-module-qtquick2
      - qml-module-qtquick-controls
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-window2
      - qml-module-qtquick-layouts
    state: present

# Install Sublime Text 3
- shell: wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

- name: Add Sublime Text Source
  template:
    src: sublime-text.list.j2
    dest: /etc/apt/sources.list.d/sublime-text.list

- name: Install Sublime Text Packages
  become: yes
  become_user: root
  apt: name=sublime-text state=latest update_cache=true
  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

# Update JAVA
- name: Add Oracle Java Source
  template:
    src: java_source.j2
    dest: /etc/apt/sources.list.d/webupd8team-java.list

- name: Add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EEA14886
    state: present
#apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886

- name: debian | set license as accepted
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java
  become: yes
  become_user: root
  apt: name=oracle-java8-installer state=latest update_cache=true
  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3
  
- name: Set Oracle Java as Default
  become: yes
  become_user: root
  apt: name=oracle-java8-set-default state=latest update_cache=true
  register: apt_res
  until: apt_res is success
  retries: 10
  delay: 3

# Install Chrome
- name: Download Chrome
  become: yes
  become_user: "{{ username }}"
  get_url: 
    url="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest="/home/{{ username }}/Downloads/google-chrome-stable_current_amd64.deb"

- name: Install Chrome
  become: yes
  become_user: root
  apt: deb="/home/{{ username }}/Downloads/google-chrome-stable_current_amd64.deb"

# Install Dropbox
- name: Download Dropbox
  become: yes
  become_user: "{{ username }}"
  get_url: 
    url="https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb"
    dest="/home/{{ username }}/Downloads/dropbox.deb"

- name: Install Dropbox
  become: yes
  become_user: root
  apt: deb="/home/{{ username }}/Downloads/dropbox.deb"

# Install Teamviewer
- name: Download Teamviewer
  become: yes
  become_user: "{{ username }}"
  get_url: 
    url="https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"
    dest="/home/{{ username }}/Downloads/teamviewer_amd64.deb"

- name: Install Teamviewer
  become: yes
  become_user: root
  apt: deb="/home/{{ username }}/Downloads/teamviewer_amd64.deb"
